version: '3.8'

services:
  jupyter-lab:
    image: dsci522_group21:0.0.2
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
        - "8888:8888"
    volumes:
      - '.:/home/jovyan'


