name: 522
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.11
    - ipython=8.17.2
    - ipykernel=6.26.0
    - jupyterlab=4.0.9
    - matplotlib=3.8.2
    - pandas=2.1.3
    - scikit-learn=1.3.2
    - altair=5.1.2
    - vl-convert-python=1.1.0
    - vegafusion=1.4.5
    - vegafusion-jupyter=1.4.5
    - pytest=7.4.3
    - dataframe_image=0.1.1
    - click=8.1.7
